SELECT bookname FROM BOOK WHERE bookid=1;
SELECT bookname FROM BOOK WHERE price >= 20000;
SELECT NAME, ADDRESS FROM CUSTOMER;
SELECT orderid FROM ORDERS WHERE orderdate BETWEEN '2014-07-04' AND '2014-07-07';
SELECT orderid FROM ORDERS WHERE NOT orderdate BETWEEN '2014-07-04' AND '2014-07-07';
SELECT NAME, ADDRESS FROM CUSTOMER WHERE NAME LIKE '±è%';
SELECT NAME, ADDRESS FROM CUSTOMER WHERE NAME LIKE '±è%¾Æ';